# Generated by Django 4.2.7 on 2023-12-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0002_alter_admin_table_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='cliente',
        ),
    ]
