# Generated by Django 4.2.7 on 2023-12-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0003_remove_veiculo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='ordem_servico',
        ),
    ]
