# Generated by Django 4.2.7 on 2023-12-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0005_remove_equipe_mecanico_equipe_mecanicos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecasordemservico',
            name='pecas',
        ),
        migrations.AddField(
            model_name='pecasordemservico',
            name='pecas',
            field=models.ManyToManyField(blank=True, to='OrdemServico.pecas'),
        ),
    ]
