# Generated by Django 4.2.7 on 2023-12-06 19:22

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0006_remove_pecasordemservico_pecas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='dataConclusao',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
