# Generated by Django 4.2.7 on 2023-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0007_alter_ordemservico_dataconclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasordemservico',
            name='pecas',
            field=models.ManyToManyField(to='OrdemServico.pecas'),
        ),
    ]
