# Generated by Django 4.2.7 on 2023-12-07 14:30

import OrdemServico.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0008_alter_pecasordemservico_pecas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrdemServico.equipe'),
        ),
        migrations.AddField(
            model_name='pecasordemservico',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='dataConclusao',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='pecasordemservico',
            name='pecas',
        ),
        migrations.AddField(
            model_name='pecasordemservico',
            name='pecas',
            field=models.ForeignKey(default=OrdemServico.models.PecasOrdemServico.get_default_peca_id, on_delete=django.db.models.deletion.CASCADE, to='OrdemServico.pecas'),
        ),
    ]
