# Generated by Django 4.2.7 on 2023-12-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0009_ordemservico_equipe_pecasordemservico_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='equipe',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='OrdemServico.equipe'),
        ),
        migrations.AlterField(
            model_name='pecasordemservico',
            name='pecas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdemServico.pecas'),
        ),
    ]
