# Generated by Django 4.2.7 on 2023-12-07 16:45

import OrdemServico.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0010_alter_ordemservico_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='equipe',
            field=models.ForeignKey(default=OrdemServico.models.Equipe.create_default_equipe, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='OrdemServico.equipe'),
        ),
    ]
