# Generated by Django 4.2.7 on 2023-12-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0011_alter_ordemservico_equipe'),
    ]

    operations = [
    ]
