# Generated by Django 4.2.7 on 2023-12-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0012_auto_20231207_1348'),
    ]

    operations = [
    ]
