# Generated by Django 4.2.7 on 2023-12-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdemServico', '0013_auto_20231207_1430'),
    ]

    operations = [
    ]
